### ISSUE TITLE
ModelSaver fails on saving Input with 2d and 3d tensors

### ISSUE THREAD

**Issue by zaleslaw** [JetBrains/KotlinDL#160]
During saving model, trained on IrisData 

```
const val SEED = 12L
const val TEST_BATCH_SIZE = 5
const val EPOCHS = 100
const val TRAINING_BATCH_SIZE = 3
const val PATH_TO_MODEL = "models/irisNet"

val model = Sequential.of(
    Input(4),
    Dense(5, Activations.Relu, kernelInitializer = HeNormal(SEED), biasInitializer = HeUniform(SEED)),
    Dense(3, Activations.Linear, kernelInitializer = HeNormal(SEED), biasInitializer = HeUniform(SEED))
)

fun main() {
    data.shuffle()

    val dataset = OnHeapDataset.create(
        ::extractX,
        ::extractY
    )

    val (train, test) = dataset.split(0.8)

    model.use {
        it.compile(optimizer = Adam(), loss = Losses.SOFT_MAX_CROSS_ENTROPY_WITH_LOGITS, metric = Metrics.ACCURACY)

        it.summary()
        it.fit(dataset = train, epochs = EPOCHS, batchSize = TRAINING_BATCH_SIZE)

        val accuracy = model.evaluate(dataset = test, batchSize = TEST_BATCH_SIZE).metrics[Metrics.ACCURACY]

        model.save(modelDirectory = File(PATH_TO_MODEL), savingFormat = SavingFormat.JSON_CONFIG_CUSTOM_VARIABLES, writingMode = WritingMode.OVERRIDE)

        println("Accuracy: $accuracy")
    }
}
```

it fails with the 

```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at org.jetbrains.kotlinx.dl.api.inference.keras.ModelSaverKt.saveModelConfiguration(ModelSaver.kt:54)
	at org.jetbrains.kotlinx.dl.api.inference.keras.ModelSaverKt.saveModelConfiguration$default(ModelSaver.kt:36)
	at org.jetbrains.kotlinx.dl.api.core.GraphTrainableModel.saveModel(GraphTrainableModel.kt:794)
	at org.jetbrains.kotlinx.dl.api.core.GraphTrainableModel.saveInKerasFormat(GraphTrainableModel.kt:788)
	at org.jetbrains.kotlinx.dl.api.core.GraphTrainableModel.save(GraphTrainableModel.kt:783)
	at org.jetbrains.kotlinx.dl.api.core.TrainableModel.save$default(TrainableModel.kt:259)
	at IrisKt.main(Iris.kt:45)
	at IrisKt.main(Iris.kt)
```

due to unfixed [TODO ](https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/ModelSaver.kt#L64)in ModelSaver

1. Please, fix the bug to handle not only images, but all situations to save the Input layer correctly to JSON config
2. It should work in both ways: for reading and for writing Input layer
3. Don't forget to add some tests for 1d and 3d data

**Comment by juliabeliaeva** [comment]
Hi, I'd like to work on this issue.

**Comment by zaleslaw** [comment]
Great, @juliabeliaeva feel free to ask any question in this issue or on Kotlin slack
