### ISSUE TITLE
Error during evalution in the example LeNetCifar10.kt

### ISSUE THREAD

**Issue by zaleslaw** [JetBrains/KotlinDL#3]
Exception in thread "main" java.lang.IllegalArgumentException: buffer with 1536000 elements is not compatible with a Tensor with shape [1000, 32, 32, 3]
	at org.tensorflow.Tensor.incompatibleBuffer(Tensor.java:580)
	at org.tensorflow.Tensor.allocateForBuffer(Tensor.java:295)
	at org.tensorflow.Tensor.create(Tensor.java:188)
	at api.keras.Sequential.evaluate(Sequential.kt:382)
	at examples.keras.cifar10.LeNetCifar10Kt.main(LeNetCifar10.kt:97)
	at examples.keras.cifar10.LeNetCifar10Kt.main(LeNetCifar10.kt)

**Comment by zaleslaw** [comment]
Fixed
